"""A bounded ReAct-style agent framework for OpenAI-compatible APIs."""

from .agent import AgentConfig, EventSink, ReActAgent, StreamSink
from .errors import ConfigurationError, ModelInvocationError, ReActAgentError
from .models import (
    AgentEvent,
    AgentResult,
    AgentStreamEvent,
    AgentStreamEventKind,
    AssistantMessage,
    EventKind,
    ModelOutcome,
    ModelRequest,
    ModelResponse,
    ModelStreamEvent,
    ModelStreamEventKind,
    ModelStreamSink,
    RunStatus,
    StopReason,
    ToolCall,
    ToolMessage,
    ToolSpec,
    Usage,
    UserMessage,
)
from .provider import ApiMode, Model, OpenAIModel, ProviderCapabilities, StreamingModel
from .tools import ApprovalHandler, ApprovalRequest, DebugExposure, Tool, ToolRegistry, tool

__all__ = [
    "AgentConfig",
    "AgentEvent",
    "AgentResult",
    "AgentStreamEvent",
    "AgentStreamEventKind",
    "ApiMode",
    "ApprovalHandler",
    "ApprovalRequest",
    "AssistantMessage",
    "ConfigurationError",
    "DebugExposure",
    "EventKind",
    "EventSink",
    "Model",
    "ModelInvocationError",
    "ModelOutcome",
    "ModelRequest",
    "ModelResponse",
    "ModelStreamEvent",
    "ModelStreamEventKind",
    "ModelStreamSink",
    "OpenAIModel",
    "ProviderCapabilities",
    "ReActAgent",
    "ReActAgentError",
    "RunStatus",
    "StopReason",
    "StreamSink",
    "StreamingModel",
    "Tool",
    "ToolCall",
    "ToolMessage",
    "ToolRegistry",
    "ToolSpec",
    "Usage",
    "UserMessage",
    "tool",
]
